# Generated by Django 3.2.8 on 2021-12-19 14:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('subcategory', models.CharField(choices=[('Mariage', (('VEF', 'Femmes'), ('CHF', 'Hommes'), ('CHF', 'Mariés'), ('SAF', 'Ensembles'), ('BEF', 'Enfants'), ('BEF', 'Accessoires'))), ('Femmes', (('VEF', 'Vêtements'), ('CHF', 'Chaussures'), ('SAF', 'Sacs'), ('BEF', 'Beauté'))), ('Hommes', (('VEH', 'Vêtements'), ('CHH', 'Chaussures'), ('SAH', 'Sacs'), ('SOH', 'Soins'))), ('Enfants', (('FI', 'Filles'), ('GA', 'Garçons'), ('JE', 'Jeux et Jouets'), ('SO', 'Soins bébé'), ('AC', 'Accessoires'))), ('Maison', (('AR', 'Arts'), ('DE', 'Décorations'), ('LI', 'Livres'), ('AC', 'Accessoires')))], max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('color', models.CharField(blank=True, choices=[('NE', 'Noir'), ('NS', 'Marron'), ('TE', 'Beige'), ('BE', 'Gris'), ('ST', 'Blanc'), ('ST', 'Bleu'), ('ST', 'Bleu pétrole'), ('ST', 'Turquoise'), ('ST', 'Vert'), ('ST', 'Vert olive'), ('ST', 'Jaune'), ('ST', 'Orange'), ('ST', 'Rouge'), ('ST', 'Rose'), ('ST', 'Violet'), ('ST', 'Doré'), ('ST', 'Argenté'), ('ST', 'Multicolore')], max_length=100, null=True)),
                ('status', models.CharField(choices=[('NE', 'Neuf avec étiquettes'), ('NS', 'Neuf sans étiquettes'), ('TE', 'Très bon état'), ('BE', 'Bon état'), ('ST', 'Satisfaisant')], max_length=100)),
                ('price', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('give', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.category')),
            ],
        ),
    ]
