# Generated by Django 3.2.8 on 2021-10-21 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='parent',
        ),
    ]
