# Generated by Django 3.2.8 on 2021-10-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_annonce_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='parent',
        ),
    ]
