# Generated by Django 3.2.8 on 2021-10-24 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0004_remove_annonce_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='souscategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='annonces.category'),
        ),
    ]
