# Generated by Django 3.2.8 on 2021-10-18 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='user.png', null=True, upload_to='photos')),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, choices=[('Dakar', 'Dakar'), ('Pikine', 'Pikine'), ('Touba', 'Touba'), ('Guediawaye', 'Guédiawaye'), ('Thies', 'Thiès'), ('Kaolack', 'Kaolack'), ('Mbour', 'Mbour'), ('SaintLouis', 'Saint-Louis'), ('Rufisque', 'Rufisque'), ('Ziguinchor', 'Ziguinchor'), ('Diourbel', 'Diourbel'), ('Tambacounda', 'Tambacounda'), ('Mbacke', 'Mbacké'), ('Kolda', 'Kolda'), ('RichardToll', 'Richard-Toll'), ('Bargny', 'Bargny'), ('Tivaouane', 'Tivaouane'), ('JoalFadiouth', 'Joal-Fadiouth'), ('Dahra', 'Dahra'), ('Kaffrine', 'Kaffrine'), ('Bignona', 'Bignona'), ('Fatick', 'Fatick'), ('Velingara', 'Vélingara'), ('Bambey', 'Bambey'), ('Sebikhotane', 'Sébikhotane'), ('Dagana', 'Dagana'), ('Sedhiou', 'Sédhiou'), ('Nguekhokh', 'Nguékhokh'), ('Diawara', 'Diawara'), ('Kedougou', 'Kédougou'), ('Kayar', 'Kayar'), ('Matam', 'Matam'), ('Meckhe', 'Meckhe'), ('Nioro', 'Nioro'), ('Ourossogui', 'Ourossogui'), ('Kebemer', 'Kébémer'), ('Ndioum', 'Ndioum'), ('Koungheul', 'Koungheul'), ('Guinguineo', 'Guinguinéo'), ('Linguere', 'Linguère'), ('Khombole', 'Khombole'), ('Bakel', 'Bakel'), ('Sokone', 'Sokone'), ('Diamniadio', 'Diamniadio'), ('Mboro', 'Mboro'), ('Thiadiaye', 'Thiadiaye'), ('Goudomp', 'Goudomp'), ('Podor', 'Podor'), ('Goudomp', 'Goudomp'), ('Gossas', 'Gossas'), ('Kanel', 'Kanel'), ('Rosso', 'Rosso'), ('Ndoffane', 'Ndoffane'), ('Gandiaye', 'Gandiaye')], default='Dakar', max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('instagram', models.URLField(blank=True, max_length=400, null=True)),
                ('facebook', models.URLField(blank=True, max_length=400, null=True)),
                ('youtube', models.URLField(blank=True, max_length=400, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
